CREATE TABLE IF NOT EXISTS enrolled(
	id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
	student_id UUID NOT NULL REFERENCES users(id),
	course_id UUID NOT NULL REFERENCES courses(id),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);